# This is a basic workflow to help you get started with Actions

name: Clean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  clean:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: devel

      - name: Delete old clean branch
        run: git branch -D clean
        continue-on-error: true

      - name: Create new clean branch
        run: git branch clean devel
     
      - name: Delete personal files
        run: |
          rm -rf .minecraft/saves
          rm -rf server/*world
          rm -rf .minecraft/XaeroWaypoints*
          rm -rf {.minecraft,server}/{logs,crash-reports}
      
      - name: Generate commit
        run: |
          git add -A
          git commit -m "This is the clean branch. Commits here will be lost." -m "Commit to the devel branch to prevent change resetting."
          
          
